### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by RezaShaban** [arqueror/Xamarin.Forms-RadialMenu#2]
when i install this plugin to pcl project =>
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Xamarin.Forms.RadialMenu 1.0.1.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by arqueror** [comment]
Hello. Project only supports .Net Standard libraries 😞, so for use it in your portable class library please include the code into your PCL manually from the source code, it's pretty straight forward. I will try to add backward-compatibility in the near future.

Cheers and thanks for the feedback!
