### ISSUE TITLE
Menu Item's location get disturbed On device Orientation change

### ISSUE THREAD

**Issue by M0Bilal** [arqueror/Xamarin.Forms-RadialMenu#3]
I have implemented radial menu with items on every location. On Portrait mode everything is good. Problem arises when:
 - I rotate the device from portrait to landscape
 - I launch the app in landscape mode

The menu items loses their location and either get hidden or out of the circle. 

**Edit:**
My bad, this was some layout bound problem. Radial menu was not able to scale properly. So this is not a bug. Closing the issue.

by the way, Thanks for the great plugin! :-)

**Comment by arqueror** [comment]
Glad it got solved. Thanks for the comment 😄
