### ISSUE TITLE
Xamarin Forms 4 compatibility

### ISSUE THREAD

**Issue by muratonal** [arqueror/Xamarin.Forms-RadialMenu#7]
Very nice work, congratulations. But can you make it work with xamarin form 4 version.It gives dependency errors on Android side with xamarin form 4

**Comment by arqueror** [comment]
Hello :D,

Thanks for your kind words. I'm already working on this and i almost have it. Hopefully i will release a new version next week with support for Xamarin.Forms 4.5.

Thanks!

**Comment by arqueror** [comment]
@muratonal So, i just pushed changes to master for adding support for Xamarin.Forms 4.5 and Android 9.0. Will close this issue once i publish NuGet package update next week. If you need this package sooner  please download source code and compile binaries by yourself.

Thanks 👍

**Comment by muratonal** [comment]
Finaly, I did so too. Thanks,
Well, can it be added to stay on open continuously?

**Comment by arqueror** [comment]
Yeah, probably it can be added and open it when needed ;) .
