### ISSUE TITLE
Menu Close Button Tapped Event

### ISSUE THREAD

**Issue by mehmetcirak** [arqueror/Xamarin.Forms-RadialMenu#9]
tnx for plugin , my question is how can I fire menu close button tapped event. I searched but could not find such an event.

**Comment by arqueror** [comment]
Hello @mehmetcirak 

Currently Menu only fires 2 events as described in docs:

 Menu.ItemTapped and   Menu.ChildItemTapped. I think center button does not exposes the event when tapped.

I will include it in next release for sure.

**Comment by arqueror** [comment]
@mehmetcirak just pushed new packjage 2.0.2 with 2 new events:

*MenuClosed
*MenuOpened

Hope it works 👍
